### ISSUE TITLE
AWS ALB CNAME support

### ISSUE THREAD

**Issue by robertmiles3** [cytopia/docker-bind#12]
I tried adding a CNAME to EXTRA_HOSTS and it bombs with...

```
Invalid IP address 'internal-foo-bar-baz-1234567890.us-east-1.elb.amazonaws.com': for sandbox.example.com -> internal-foo-bar-baz-1234567890.us-east-1.elb.amazonaws.com. Skipping to add extra host
```

Based on the error message, maybe the `is_cname` isn't picking this up properly?

**Comment by robertmiles3** [comment]
It's like this...

```
EXTRA_HOSTS=sandbox.example.com=internal-foo-bar-baz-1234567890.us-east-1.elb.amazonaws.com
```

But, looking at your code for this, it may not work anyway. It looks like you just resolve the cname to an IP and add that IP to the list. However, AWS ALB's rotate IPs randomly so it likely won't work.

**Comment by cytopia** [comment]
What does `host internal-foo-bar-baz-1234567890.us-east-1.elb.amazonaws.com` output?

**Comment by cytopia** [comment]
Regex fix PR is open. Keep in mind that you need to quote the values for EXTRA_HOSTS like so:

```
EXTRA_HOSTS='sandbox.example.com=internal-foo-bar-baz-1234567890.us-east-1.elb.amazonaws.com'
```
