### ISSUE TITLE
problem with reverse resolution and multiple EXTRA_HOSTS

### ISSUE THREAD

**Issue by eleaner** [cytopia/docker-bind#16]
following the readme, I try to resolve two hosts like below
```
docker service create \
  --name bind-dns \
  -p 53:53/tcp \
  -p 53:53/udp \
  -e EXTRA_HOSTS='hetzner1=10.8.0.5=hetzner1,hetzner2=10.8.0.9=hetzner2' \
  cytopia/bind
 ```
and I get following log with error error - docker service fails
```
bind-dns.1.8wkm3glijglg@kimsufi1    | [INFO] Debug level: 1
bind-dns.1.8wkm3glijglg@kimsufi1    | [INFO] Using default DNS TTL time: 3600 sec
bind-dns.1.8wkm3glijglg@kimsufi1    | [INFO] Using default DNS Refresh time: 1200 sec
bind-dns.1.8wkm3glijglg@kimsufi1    | [INFO] Using default DNS Retry time: 180 sec
bind-dns.1.8wkm3glijglg@kimsufi1    | [INFO] Using default DNS Expiry time: 1209600 sec
bind-dns.1.8wkm3glijglg@kimsufi1    | [INFO] Using default DNS Max Cache time: 10800 sec
bind-dns.1.8wkm3glijglg@kimsufi1    | [INFO] Adding extra host: hetzner1 -> 10.8.0.5 (PTR: hetzner1)
bind-dns.1.8wkm3glijglg@kimsufi1    | [INFO] Adding extra host: hetzner2 -> 10.8.0.9 (PTR: hetzner2)
bind-dns.1.8wkm3glijglg@kimsufi1    | [INFO] DNSSEC Validation: no
bind-dns.1.8wkm3glijglg@kimsufi1    | [INFO] Adding custom DNS forwarder: 8.8.8.8,8.8.4.4
bind-dns.1.8wkm3glijglg@kimsufi1    | [INFO] Starting BIND 9.11.4
bind-dns.1.8wkm3glijglg@kimsufi1    | /etc/bind/devilbox-extra_hosts.hetzner2.conf:7: zone '0.8.10.in-addr.arpa': already exists previous definition: /etc/bind/devilbox-extra_hosts.hetzner1.conf:7
```

Everything is working fine with only one specified host.
If I try to define EXTRA_HOST twice, the last one wins

**Comment by science695** [comment]
Why are you including the dns name twice? It is intended to be a pair hostname=ipaddress,...

> EXTRA_HOSTS=mywebserver.loc=172.16.238.1
https://devilbox.readthedocs.io/en/latest/advanced/add-custom-cname-records.html?highlight=extra%20hosts

and, to match that to your case:

> -e EXTRA_HOSTS='hetzner1=10.8.0.5,hetzner2=10.8.0.9'

**Comment by eleaner** [comment]
Please see section 5. Adding reverse DNS:
https://github.com/cytopia/docker-bind
`The following extra host 'my.host' is added and will always point to whatever
 IP example.org resolves to.
 As well as adding reverse DNS from 192.168.0.1 to resolve to tld
EXTRA_HOSTS='tld=192.168.0.1=tld'`

my requirement is to resolve hetzner1 -> 10.8.0.5 as well as 10.8.0.5 -> hetzner1
and it works as long as I have only one entry

**Comment by science695** [comment]
Oh, I'm sorry. It looks like the developer added a feature I didn't know about.

@cytopia: eleaner has found a bug with multiple extra_hosts with reverse lookup.

If you do:
`EXTRA_HOSTS=test.loc=someip,test2.loc=someotherip`

The configuration it creates returns an error:
`/etc/bind/devilbox-extra_hosts.test2.loc.conf:7: zone '238.16.172.in-addr.arpa': already exists previous definition: /etc/bind/devilbox-extra_hosts.test.loc:7`

This is caused by always adding in a zone for the subnet for every extra host with reverse:
https://github.com/cytopia/docker-bind/blob/master/data/docker-entrypoint.sh#L248

I'm not sure what you were solving by adding that subnet zone, but you might want to track with subnets you've added a zone and not add duplicate zones.

**Comment by cytopia** [comment]
Good catch. I will probably have to create multiple zones then

**Comment by dimkasta** [comment]
Since this is mostly intended for internal use, adding the reverse zone could be implicit for all cases? Just a thought

**Comment by mboehm21** [comment]
Is there already a way to get the reverse-lookup working again?
Is there also a way to round-robin load-balance with this dns-server?

Thanks for creating this really nice image, by the way.

**Comment by cytopia** [comment]
@eleaner @science695 @dimkasta @mboehm21 

@Rakiah  thanks for the issue. I have made a major rewrite which addresses the fix here: https://github.com/cytopia/docker-bind/pull/36
