### ISSUE TITLE
Cannot route all subdomains to an IP except the domain itself

### ISSUE THREAD

**Issue by Rakiah** [cytopia/docker-bind#17]
Hello
The way the WILDCARD_DNS parameter is used we cannot use it without having to map the domain aswell,
and using something like *.DOMAIN.com is not supported by the system,

how would I let domain.com handled by normal dns (8.8.8.8 for example) and all its subdomain handled by bind ?

Thanks

**Comment by cytopia** [comment]
@Rakiah  thanks for the issue. I have made a major rewrite which addresses the fix here: https://github.com/cytopia/docker-bind/pull/36
