### ISSUE TITLE
container keeps crashing/restarting

### ISSUE THREAD

**Issue by ericp-mrel** [cytopia/docker-bind#38]
For some reason, my container keeps crashing/restarting, but I'm not sure what error exactly is causing this behavior.
I'm using v0.27 of this container with devilbox if that helps.

Here's the logs: https://pastebin.com/cWLZL4r2

**Comment by cytopia** [comment]
> Seems like it's much more stable now and not crashing constantly.

That tells me the issue has been resolved, no?

**Comment by ericp-mrel** [comment]
Sorry, yes it is resolved for me.
