### ISSUE TITLE
[Question]: How do i use host.docker.internal while this service is active

### ISSUE THREAD

**Issue by b-strauss** [cytopia/docker-bind#63]
### Have you already checked elsewhere?

- [X] I have checked existing issues
- [x] I have googled already with no luck
- [ ] I have not done any of the above

### What is your question?

I need to use xdebug to debug something in php. Normally you can use the special DNS name 'host.docker.internal' from docker to connect xdebug to the host system. But when cytopia/bind is active xdebug can't establish a connection. If I disable cytopia/bind, it's working. Is there something I need to configure to make this work while cytopia/bind is active?

### What have you tried already?

Different environment configurations.

### What is your goal?

Make xdebug work.

**Comment by vikas5914** [comment]
@b-strauss Have you tried this : https://devilbox.readthedocs.io/en/latest/intermediate/configure-php-xdebug.html

**Comment by b-strauss** [comment]
I was able to solve it by setting this on the php container service.

```yaml
  extra_hosts:
    - host.docker.internal:host-gateway
```
